CSenshi/Validator

- test.py
- tests/rules/test_between.py
- validator/rules_src/between.py
Implementation of between rule, the very example of how to inherit from different rules and create new one.
> New Rule: Between

- .github/workflows/pythonpackage.yml
- Makefile
- requirements.txt
- tests/__parser__/test_translator.py
fix the urgent bug as said in Issue
> Fix formatting (#15)

- requirements.txt
- tests/__parser__/test_translator.py
- tests/rules/test_required_if.py
- utils/generate_rules_import.py
- validator/__parser__/translator.py
- validator/rules_src/__init__.py
- validator/rules_src/required_if.py
This PR fixes bug mentioned in #14. In addition new rule 'required_if' is implemented.
> Fix multiple named rules and add required_if rule  

- requirements.txt
- validator/__parser__/translator.py
- validator/rules_src/__init__.py
Fix Translator class bugs.
for now it can translate strings,arrays and Rule's classes to Rule's instance
> Fix translator bugs

- tests/rules/test_required.py
- validator/rules_src/required.py
fixed Missing tests for Required #5
> Required test

- tests/test_validator.py
- validator/rules_src/__init__.py
- validator/rules_src/between.py
- validator/rules_src/mail.py
- validator/rules_src/max.py
- validator/rules_src/min.py
- validator/rules_src/required.py
- validator/rules_src/required_if.py
- validator/validator.py
Added error messages for each class and errors return argument to the validator.
Error mesages in Rule classes #3
> Error messages

- CONTRIBUTING.md
- Makefile
- utils/generate_rule_sample.py
- utils/rule_template.txt
- utils/test_template.txt
Fix #1 add template files for rules and test alongside the rule generator file
> Rule generator

- validator/__init__.py
- validator/__parser__/translator.py
- validator/errors.py
- validator/exceptions.py
- validator/validator.py
Implementation of some custom exceptions and checkers.
> Error handling

- tests/__parser__/__init__.py
- tests/__parser__/test_parse.py
- tests/__parser__/test_parser.py
- tests/rules/__init__.py
Completed tests for the parser class and added empty init files to rules and parser subdirectories, so they will behave as packages
> Parser tests

- tests/rules/test_between.py
- tests/rules/test_mail.py
- tests/rules/test_max.py
- tests/rules/test_min.py
- tests/rules/test_required.py
- tests/rules/test_required_if.py
- tests/test_validator.py
- utils/generate_rules_import.py
- validator/__init__.py
- validator/rules_src/__init__.py
- validator/rules_src/between.py
- validator/rules_src/mail.py
- validator/rules_src/max.py
- validator/rules_src/min.py
- validator/rules_src/required.py
- validator/rules_src/required_if.py
- validator/validator.py
Changed `__call __ ()` to `check ()`. Also simplified doctests.
#28
> Changed __call__() to check()

- tests/test_validator.py
- validator/__init__.py
- validator/validator.py
Added array validation via `validate_many` function. 
#31
> Added validate_many()

- tests/__parser__/test_translator.py
- tests/rules/test_between.py
- tests/rules/test_max.py
- tests/rules/test_min.py
- validator/__parser__/translator.py
add bad tests for translator class.
> Translator testing

- tests/rules/test_IP.py
- tests/rules/test_IPv4.py
- tests/rules/test_IPv6.py
- validator/rules_src/IP.py
- validator/rules_src/IPv4.py
- validator/rules_src/IPv6.py
IPv4, IPv6 validation rules implementation
> Ip validator

- tests/__parser__/test_translator.py
- tests/test_validator.py
- validator/__parser__/translator.py
From #30 
1) Figured, that if rules contain key(s) that's not in the request, the error should occur
2) Fixed this problem
> Fix empty rule problem

- MANIFEST.in
- README.md
- setup.py
- utils/readme/README_EXAMPLE.md
Uploaded package on pip. View at:
https://pypi.org/project/validator/
get package using:
`pip install validator`
> Pip publish

- README.md
- tests/rules/test_integer.py
- tests/rules/test_list.py
- tests/rules/test_size.py
- tests/test_rpv.py
- validator/rule_pipe_validator.py
- validator/rules_src/__init__.py
- validator/rules_src/integer.py
- validator/rules_src/list.py
- validator/rules_src/size.py
- validator/validator.py
Create new class RPV (RulePipeValidator), which is responsible for connecting rules with each other.
Example:
```python
request = {"age": 23}
rule = {"age": "size:23"}
result = Validator(request, rule).validate() # False
request = {"age": 23}
rule = {"age": "integer|size:23"}
result = Validator(request, rule).validate() # True
```
Please see tests for rpv for more examples `tests/test_rpv.py`
> Add rules interconnection

- RULES.md
- tests/rules/test_same.py
- validator/parser/translator.py
- validator/rule_pipe_validator.py
- validator/rules_src/__init__.py
- validator/rules_src/same.py
- validator/rules_wrapper.py
- validator/validator.py
New Feature for rules to interact with each other. RPV is interface for same data field rules. We created RW (RulesWrapper) which is responsible for connecting distinct fields
> Validator fields

- RULES.md
- utils/generate_rule/generate_rule_sample.py
- utils/generate_rule/rule_template.txt
- utils/readme/generate_readme.py
- validator/rules_src/IP.py
- validator/rules_src/IPv4.py
- validator/rules_src/IPv6.py
- validator/rules_src/between.py
- validator/rules_src/integer.py
- validator/rules_src/list.py
- validator/rules_src/mail.py
- validator/rules_src/max.py
- validator/rules_src/min.py
- validator/rules_src/required.py
- validator/rules_src/size.py
This PR will change all the doctests from using Rule class instances to using normal validation
> Change tests

- RULES.md
- tests/rules/test_regex.py
- validator/rules_src/regex.py
Closes #62.
My other thought on this is that the `Mail` rule could easily be changed to use this new `Regex` rule. Thoughts?
> Add Regex rule

- Makefile
- README.md
- setup.py
- tests/test_custom_rules.py
- tests/test_validator.py
- validator/rules_wrapper.py
- validator/validator.py
following PR adds ability to return validated_data. 
```python3
result, validated_data, errors = validate_many(reqs, rule, return_info=True)
```
See readme for futher explanation
> Validated data

- tests/rules/test_IP.py
- tests/rules/test_IPv4.py
- tests/rules/test_IPv6.py
- tests/rules/test_between.py
- tests/rules/test_integer.py
- tests/rules/test_list.py
- tests/rules/test_mail.py
- tests/rules/test_max.py
- tests/rules/test_min.py
- tests/rules/test_regex.py
- tests/rules/test_required.py
- tests/rules/test_same.py
- tests/rules/test_size.py
Added string tests to all of the rules.
Closes #59
> Add string tests

- RULES.md
- tests/rules/test_string.py
- validator/rules_src/string.py
I added new rule for string validation as it was mentioned in this [issue](https://github.com/CSenshi/Validator/issues/51)
> Add new rule for string validation

- RULES.md
- tests/rules/test_hex.py
- validator/rules_src/hex.py
Add hex rule implementation accordingly to #90
> add hex rule implementation

- tests/parser/test_accepted.py
- validator/rules_src/accepted.py
As requested in issue #88  this adds new rule set: accepteds.
> New Rule: Accepteds

- tests/rules/test_size.py
tested list, dict, json, string size
> tested list, dict, json, string size

- tests/rules/test_size.py
> Num system tests

- tests/rules/test_base32.py
- tests/rules/test_base64.py
- tests/rules/test_between.py
- tests/rules/test_dict.py
- tests/rules/test_required_if.py
- tests/test_custom_rules.py
- tests/test_rpv.py
removed unused imports from test classes
> removed unused imports from test classes
